const env = require('./index').NODE_ENV;

const Emails = {
  test: {
    registrationEmail: ['test@example.com'],
    projectEmail: ['test@example.com'],
    projectEmailLead: ['test@example.com'],
    listingEmail: ['test@example.com'],
    contactEmail: ['test@example.com'],
    contactCCEmail: ['test@example.com'],
    threePlMail: ['test@example.com'],
    ratesInquiryEmail: ['test@example.com'],
    estesMail: ['test@example.com'],
    EFWMail: ['test@example.com'],
    kuebixMail: ['test@example.com'],
    chrobinsonEmail: ['test@example.com'],
    JLLEmail: ['test@example.com'],
    supportMail: ['test@example.com'],
    ticketSupportMail: ['test@example.com'],
    noQuoteSubmitted: ['test@example.com'],
    lessThan7Warehouses: ['test@example.com'],
    rateScreenEncountered: ['test@example.com'],
    projectExpiredInactiveEmail: ['test@example.com'],
    threePl_interested_in_referral_support: ['test@example.com'],
    invoiceDisputedTwice: ['test@example.com'],
    invoicePaymentFailedThirdTime: ['test@example.com'],
    dailyReport: ['test@example.com'],
    demoRequest: ['test@example.com']
  },

  staging: {
    registrationEmail: ['nirmal@shiptime.com'],
    projectEmail: ['nirmal@shiptime.com'],
    projectEmailLead: ['nirmal@shiptime.com'],
    listingEmail: ['nirmal@shiptime.com'],
    contactEmail: ['nirmal@shiptime.com'],
    contactCCEmail: ['nirmal@shiptime.com'],
    estesMail: ['nirmal@shiptime.com'],
    EFWMail: ['nirmal@shiptime.com'],
    kuebixMail: ['nirmal@shiptime.com'],
    chrobinsonEmail: ['nirmal@shiptime.com'],
    JLLEmail: ['nirmal@shiptime.com'],
    supportMail: ['nirmal@shiptime.com'],
    ticketSupportMail: ['nirmal@shiptime.com'],
    noQuoteSubmitted: ['nirmal@shiptime.com'],
    lessThan7Warehouses: ['nirmal@shiptime.com'],
    rateScreenEncountered: ['nirmal@shiptime.com'],
    threePlMail: ['nirmal@shiptime.com'],
    ratesInquiryEmail: ['nirmal@shiptime.com'],
    projectExpiredInactiveEmail: ['nirmal@shiptime.com'],
    threePl_interested_in_referral_support: ['nirmal@shiptime.com'],
    invoiceDisputedTwice: ['nirmal@shiptime.com'],
    invoicePaymentFailedThirdTime: ['nirmal@shiptime.com'],
    dailyReport: ['nirmal@shiptime.com'],
    demoRequest: ['nirmal@shiptime.com']
  },

  production: {
    registrationEmail: ['support@warehowz.com'],
    projectEmail: ['support@warehowz.com'],
    projectEmailLead: ['support@warehowz.com'],
    listingEmail: ['support@warehowz.com'],
    contactEmail: ['support@warehowz.com'],
    contactCCEmail: ['sales@warehowz.com', 'support@warehowz.com'],
    estesMail: ['rich@warehowz.com'],
    EFWMail: ['support@warehowz.com', 'rich@warehowz.com'],
    kuebixMail: ['support@warehowz.com', 'rich@warehowz.com'],
    chrobinsonEmail: ['support@warehowz.com', 'rich@warehowz.com'],
    JLLEmail: ['support@warehowz.com', 'rich@warehowz.com'],
    supportMail: ['support@warehowz.com'],
    ticketSupportMail: ['rich@warehowz.com'],
    noQuoteSubmitted: ['support@warehowz.com'],
    lessThan7Warehouses: ['support@warehowz.com'],
    rateScreenEncountered: ['support@warehowz.com'],
    threePlMail: ['support@warehowz.com'],
    ratesInquiryEmail: ['support@warehowz.com'],
    projectExpiredInactiveEmail: ['support@warehowz.com'],
    threePl_interested_in_referral_support: ['support@warehowz.com'],
    invoiceDisputedTwice: ['tracey@shiptime.com'],
    invoicePaymentFailedThirdTime: ['tracey@shiptime.com'],
    dailyReport: ['support@warehowz.com'],
    demoRequest: ['sales@warehowz.com']
  }
};

module.exports = Emails[env];
