name: Deploy Production to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v6

      # Step 2: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_PROD }}

      # Step 3: Setup gcloud CLI
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID_PROD }}

      # Step 4: Build Docker image in Cloud Build and push to Artifact Registry
      - name: Build & Push Docker image
        run: |
          gcloud builds submit . \
            --tag us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID_PROD }}/warehowz-cron/warehowz-cron-service:production

      # Step 5: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy warehowz-cron-service \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID_PROD }}/warehowz-cron/warehowz-cron-service:production \
            --region ${{ secrets.GCP_REGION_PROD }} \
            --platform managed \
            --no-allow-unauthenticated \
            --min-instances=1 \
            --max-instances=1 \
            --no-cpu-throttling \
            --memory=1Gi \
            --set-env-vars=NODE_OPTIONS=--max-old-space-size=768 \
            --port=8080 \
            --vpc-connector=warehowz-connector \
            --vpc-egress=all-traffic
